// Recording-only sample app. Margin's review UI and production styles are untouched.
export const dashboardScript = `document.querySelector('#app').innerHTML = \`
<header><div><p class="eyebrow">WEEKLY PULSE / PRODUCT TEAM</p><h1>Your team, at a glance.</h1><p class="subtitle">September 14–20 · A steady week of progress</p></div><span class="period">This week ▾</span></header>
<div class="stats"><section><small>Active projects</small><strong>12</strong><span class="trend">+2 this month</span></section><section><small>Tasks complete</small><strong>84<span>%</span></strong><span class="trend">↑ 8% from last week</span></section><section><small>Needs attention</small><strong>3</strong><span class="warning">Review before Friday</span></section></div>
<div class="charts"><section><div class="chart-title">Team momentum <small>Completed tasks</small></div><svg viewBox="0 0 340 140" role="img" aria-label="Completed tasks trend"><g stroke="#eae8e4"><path d="M15 25H330 M15 65H330 M15 105H330"/></g><path d="M15 99L65 87L115 94L165 58L215 69L270 35L330 20V115H15Z" fill="#f2dedb"/><path d="M15 99L65 87L115 94L165 58L215 69L270 35L330 20" stroke="#ba7973" stroke-width="3" fill="none"/><g fill="#87918e" font-size="10"><text x="12" y="135">Mon</text><text x="110" y="135">Wed</text><text x="212" y="135">Fri</text><text x="310" y="135">Sun</text></g></svg></section><section><div class="chart-title">Workload</div><div class="donut"><span>48<small>tasks</small></span></div><div class="legend"><i class="sage"></i>Done <i class="ochre"></i>In progress <i class="rose"></i>At risk</div></section></div>
<footer><div class="project"><span class="dot"></span><div><b>Website refresh</b><small>Design review · On track</small></div></div><button id="export">Export</button></footer>
\`;document.querySelector('#export').onclick=()=>document.querySelector('#export').textContent='Exported';`;

export const dashboardStyles = `
*{box-sizing:border-box}body{font:13px/1.5 system-ui;color:#33433e;margin:0;padding:24px;background:#f7f8f5}header{display:flex;align-items:center;justify-content:space-between;gap:12px}.eyebrow{font-size:9px;letter-spacing:1.5px;color:#7c8d85;margin:0 0 5px}h1{font-size:24px;letter-spacing:-.7px;line-height:1.2;margin:0}.subtitle{font-size:11px;color:#7a8982;margin:8px 0 0}.period{white-space:nowrap;padding:6px 10px;border:1px solid #e3e6df;background:white;border-radius:6px;font-size:10px;color:#65746c}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:20px 0 14px}section{padding:14px;background:white;border:1px solid #e3e7df;border-radius:10px}small{display:block;color:#819087;font-size:10px}strong{display:block;font-size:30px;font-weight:650;line-height:1.25;margin:5px 0}strong span{font-size:20px}.trend,.warning{font-size:9px;color:#799687}.warning{color:#b38b54}.charts{display:grid;grid-template-columns:1.55fr 1fr;gap:12px}.chart-title{font-size:11px;font-weight:600;margin-bottom:10px}.chart-title small{font-weight:400;float:right;font-size:9px}.charts svg{display:block;width:100%;height:140px}.donut{width:100px;height:100px;border-radius:50%;margin:10px auto 14px;background:conic-gradient(#82a496 0% 58%,#d8bc79 58% 83%,#c88d85 83% 94%,#a8b9c9 94%);display:grid;place-items:center}.donut>span{display:flex;flex-direction:column;align-items:center;justify-content:center;border-radius:50%;width:74px;height:74px;background:white;font-size:23px;font-weight:600}.donut small{font-size:9px;font-weight:400}.legend{font-size:8px;color:#849088;display:flex;justify-content:center;align-items:center;gap:4px;white-space:nowrap}.legend i{display:inline-block;width:6px;height:6px;border-radius:2px;margin-left:3px}.sage{background:#82a496}.ochre{background:#d8bc79}.rose{background:#c88d85}footer{display:flex;align-items:center;justify-content:space-between;margin-top:16px;padding:12px 14px;background:#fff;border:1px solid #e3e7df;border-radius:10px}.project{display:flex;align-items:center;gap:9px}.project b{font-size:11px;font-weight:550}.dot{width:8px;height:8px;background:#82a496;border-radius:50%}button{font:11px system-ui;border:0;border-radius:6px;padding:9px 16px;color:white;background:#476c5b}
`;
